name: Build & Upload
env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1
on:
  workflow_dispatch:
  push:
    branches:
      - test
  workflow_call:
    secrets:
      ENVS:
        required: false
      REDDIT_CLIENT_ID:
        required: false
    inputs:
      CI_TEST:
        required: false
        type: boolean
        default: false
      COMMIT_CHANGELOG:
        type: boolean
        required: false
        default: true
      DEBUG_ENABLED:
        type: boolean
        description: 'Run the build with tmate debugging enabled.'
        required: false
        default: false
      PREFERRED_PATCH_APPS:
        description: "Apps to be patched. Overrides any env set"
        required: false
        type: string

jobs:
  build-apk:
    permissions: write-all
    name: APK Build
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Check out Git repository
        uses: actions/checkout@main

      - name: Update Env for custom build
        run: |
          echo "${{ secrets.ENVS }}" >> .env
          echo "GITHUB_REPOSITORY=${{ github.repository }}" >> .env

      - name: Update Env from secrets for custom build
        run: |
          echo "${{ secrets.DOCKER_PY_REVANCED_SECRETS }}" >> .env
          echo "Added envs"
          echo "${{ secrets.DOCKER_PY_REVANCED_SECRETS }}"